fix bug, convention
QuanNH97/DemoNewFeeds pull request #1
Opened 2020-08-26 03:20 UTC by QuanNH97

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DataHelper.swift
> +func randomComment() -> [Comment] {
E tham khảo cách viết này cho ngắn gọn nhé.
func randomComment() -> [Comment] {
    return 1...15.map { _ -> Comment? in 
        guard
            let author = users.randomElement(),
            let content = paramArr.randomElement(),
            let time = timeMinute.randomElement()
        else {
            return nil
        }
        return Comment(author: User(name: author), postedTime: time, content: content)
    }
    .compactMap { $0 }
    .sort { $0.postedTime > $1.postedTime }
}
Bên cạnh đó hàm của e nếu có 1 case trong guard là false thì sẽ luôn trả về mảng rỗng, không hợp lý lắm.

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DataHelper.swift
> +func randomPost() -> [Post] {
nhận xét tương tự như hàm randomComment ở trên

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailPostTableViewCell.swift
>      @IBOutlet weak var cmtTime: UILabel!
đặt lại tên label. Viết rõ là commentTimeLabel. Tương tự với các outlet khác.

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailPostTableViewCell.swift
>          if self.post.like == 1 {
thừa self

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailPostTableViewCell.swift
>          self.avatarImage.image = UIImage(named: post.author.avatar)
thừa self, tương tự với các dòng dưới

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailPostTableViewCell.swift
> +        self.cmtImage.image = UIImage(named: comment.author.avatar)
thừa self

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailViewController.swift
> +        detailPost.separatorStyle = .none
sửa thành detailPostTableView hoặc tableView. Tên outlet đang bị tối nghĩa

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailViewController.swift
>          self.navigationController?.navigationBar.tintColor = .gray
thừa self

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailViewController.swift
>              let cell = detailPost.dequeueReusableCell(withIdentifier: "detailPost", for: indexPath) as! DetailPostTableViewCell
không force unwrap. Sử dụng if let hoặc guard let

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/DetailViewController.swift
>              let cell = detailPost.dequeueReusableCell(withIdentifier: "moreComment", for: indexPath) as! DetailPostTableViewCell
không force unwrap. Sử dụng if let hoặc guard let

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
> +    var data = randomPost()
private biến nếu không gọi ở bên ngoài class

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
>          let post = data[indexPath.row]
có thể có 1 bước check xem có tồn tại index của mảng data là indexPath.row hay không bằng indices

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
>              cell.selectionStyle = .none
tạo 1 hàm setupUI gì đó trong cell, đặt dòng này ở trong đó thay vì ngoài này

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
>              cell.selectionStyle = .none
tạo 1 hàm setupUI gì đó trong cell, đặt dòng này ở trong đó thay vì ngoài này

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
>              let cell = newFeedsTableView.dequeueReusableCell(withIdentifier: "lastPost", for: indexPath) as! PostTableViewCell
không force unwrap

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/NewFeedsViewController.swift
>              let cell = newFeedsTableView.dequeueReusableCell(withIdentifier: "post", for: indexPath) as! PostTableViewCell
không force unwrap

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/PostTableViewCell.swift
>          let parenTable = self.superview as! UITableView
không force unwrap

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/PostTableViewCell.swift
>      @IBAction func likeAction(_ sender: Any) {
action để ở dưới cùng, không để ngay sau outlet

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/PostTableViewCell.swift
> +        self.post = post
thừa self

2020-08-26 04:50 UTC, thanhhvt7196 commented on DemoNewFeeds/PostTableViewCell.swift
> +        self.reaction.text = post.shareCount == 0 ? "\(post.reactCount) - \(post.comment.count) comment" : "\(post.reactCount) - \(post.comment.count) comment - \(post.shareCount) share"
thử tìm cách viết khác ngắn gọn và clear hơn nếu như phải check cả reactCount, commentCount

2020-08-27 06:50 UTC, mlh-hieutq requested changes

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/PostTableViewCell.swift
> +    @IBOutlet weak var avatarImage: UIImageView!
Em sửa **avatarImage** thành **avatarImageView**

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/PostTableViewCell.swift
> +    @IBOutlet weak var postImage: UIImageView!
Em sửa postImage thành postImageView

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/PostTableViewCell.swift
> +    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
Viết rõ bottomConstraint của đối tượng nào. Ví dụ **likeLabelBottomConstraint**

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/PostTableViewCell.swift
> +        bottomConstraint.constant = row == dataCount - 1 ? 105 : 55
Khai báo hằng số cho **105** và **55**

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/LastCommentTableViewCell.swift
> +    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
Sửa **cmt** thành **comment**
**cmtImage** thành **cmtImageView**
Viết rõ **bottomConstraint**

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/DetailViewController.swift
> +        configTable()
Sửa **configTable** thành **configTableView**
Bỏ đoạn này vào trong configTableView
detailPostTableView.delegate = self
detailPostTableView.dataSource = self

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/DetailViewController.swift
> +            let cell = detailPostTableView.dequeueReusableCell(withIdentifier: "PostTableViewCell", for: indexPath) as! PostTableViewCell
Không sử dụng force cast

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/DetailViewController.swift
> +            let cell = detailPostTableView.dequeueReusableCell(withIdentifier: "MoreCommentTableViewCell", for: indexPath) as! MoreCommentTableViewCell
Không sử dụng force cast

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/DetailViewController.swift
> +            let cell = detailPostTableView.dequeueReusableCell(withIdentifier: "LastCommentTableViewCell", for: indexPath) as! LastCommentTableViewCell
Không sử dụng force cast

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/DetailViewController.swift
> +            let cell = detailPostTableView.dequeueReusableCell(withIdentifier: "CommentTableViewCell", for: indexPath) as! CommentTableViewCell
Không sử dụng force cast

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/NewFeedsViewController.swift
> +        configTable()
Sửa configTable thành configTableView
Bỏ đoạn này vào trong configTableView
detailPostTableView.delegate = self
detailPostTableView.dataSource = self

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/NewFeedsViewController.swift
> +        navigationItem.title = "New Feeds"
Phần này để ra ngoài một hàm khác chẳng hạn **setupNavigationTitle()**
navigationItem.title = "New Feeds"

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/NewFeedsViewController.swift
> +            detailVC = storyboard?.instantiateViewController(withIdentifier: "detailVC") as? DetailViewController
Sửa **detailVC** thành **detailViewController**

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/ViewController/NewFeedsViewController.swift
> +        cell.configCell(row: indexPath.row, dataCount: data.count)
Truyền luôn Post vào trong configCell(). Không cần gọi insertData() ở ngoài nữa.

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/CommentTableViewCell.swift
> +    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
Sửa tương tự ở trên

2020-08-27 06:50 UTC, mlh-hieutq commented on DemoNewFeeds/Views/PostTableViewCell.swift
> +        bottomConstraint.constant = row == dataCount - 1 ? 105 : 55
Sử dụng ContentInset hoặc add Footer cho tableView thay vì thay đổi chiều cao của cell cuối cùng

2020-08-27 09:31 UTC, mlh-hieutq approved these changes

2020-08-27 09:38 UTC, thanhhvt7196 approved these changes

2020-09-01 03:01 UTC, merged